#!/data/data/com.termux/files/usr/bin/bash
#Studio Mr.ALeonws

echo -e "\e[1;36m            ==========STUDIO MR.ALEONWS==========\n"
echo -e "\e[1;32m
           ░░┌──┐░░░░░░░░░░┌──┐░░ 
           ░╔╡▐▐╞╝░░┌──┐░░╔╡▐▐╞╝░ \033[91m   CREADO POR:\033[92m
           ░░└╥╥┘░░╚╡▌▌╞╗░░└╥╥┘░░ \033[94m   MR.ALEONWS\033[92m
           ░░░╚╚░░░░└╥╥┘░░░░╚╚░░░ 
           ░░░░░░░░░░╝╝░░░░░░░░░░\033[93m NUNCA DEJES DE APRENDER PAPU\033[93m
\n"
echo -e "\e[1;35m==================================\n"
echo -e "\e[1;34m Para Solo Audio Presiona [ 1 ]\n"
echo -e "\e[1;33m Para Video 360p Presiona [ 2 ]\n"
echo -e "\e[1;32m Para Video 480p Presiona [ 3 ]\n"
echo -e "\e[1;35m Para Video 720p Presiona [ 4 ]\n"
echo -e "\e[1;31m Para Video 1080p Presiona [ 5 ]\n"
echo -e "\e[1;35m==================================\n"
echo -e "\e[1;33m"
echo -n "SELECCIONE UNA OPCION :"

command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s -f'
read option

if [ "$option" -eq "1" ]
then
    echo "$command 140" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "2" ]
then
    echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "3" ]
then
    echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "4" ]
then
    echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "5" ]
then
    echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config
    youtube-dl $1
fi
